requirejs.config({
    paths:{
        "jquery":"./js/jquery-3.3.1.min",
        "index":"./model/index",
        "scroll":"./js/scroll",
        "lunbo":"./js/lunbo",
        "lunbo1":"./js/lunbo1",
        "buttonhover":"./js/buttonhover",
        "mask":"./js/mask",
        "login_register":"./js/login_register",
        "top":"./js/top"
    }
})